import type { Metadata } from "next";
import "./globals.css";
import { SocketProvider } from "@/utils/context/SocketContext";
import UserNotifications from "@/components/Notification/UserNotifications";
// import PreventRefreshProvider from "@/utils/hooks/PreventRefreshProvider";

export const metadata: Metadata = {
  title: "Tic-Tac-Toe",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased bg-seconday flex justify-center items-center`}
      >
        <main className="h-[90%] w-[90%] text-white rounded-xl flex flex-row justify-between items-center gap-6">
          {/* <PreventRefreshProvider shouldPrevent={true}> */}
          <SocketProvider>
            <UserNotifications />

            {children}
          </SocketProvider>
          {/* </PreventRefreshProvider> */}
        </main>
      </body>
    </html>
  );
}
