import type { Metadata } from "next";
import "./globals.css";
// import PreventRefreshProvider from "@/utils/hooks/PreventRefreshProvider";

export const metadata: Metadata = {
  title: "Tic-Tac-Toe",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased bg-seconday flex justify-center items-center`}
      >
        {/* <PreventRefreshProvider shouldPrevent={true}> */}
        {children}
        {/* </PreventRefreshProvider> */}
      </body>
    </html>
  );
}
